# Generated by Django 2.2.28 on 2023-01-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20230117_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='subscription',
        ),
    ]
