# Generated by Django 2.2.28 on 2023-01-18 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(1, 'the field must contain at least 1 characters')], verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='application',
            name='domain_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='framework',
            field=models.CharField(blank=True, choices=[('WEB', 'Django'), ('MOBILE', 'React Native')], max_length=50, verbose_name='Framework'),
        ),
        migrations.AddField(
            model_name='application',
            name='type',
            field=models.CharField(blank=True, choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
    ]
