# Generated by Django 2.2.28 on 2023-01-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20230118_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='domain_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Domain Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='framework',
            field=models.CharField(choices=[('WEB', 'Django'), ('MOBILE', 'React Native')], default=None, max_length=50, verbose_name='Framework'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile')], default=None, max_length=50, verbose_name='Description'),
        ),
    ]
